remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - "Full Stack Developer"
  - "Software Engineer"

locations:
  - "India"
  - "Remote"

distance: 100

companyBlacklist:
  - "Company1"
  - "Company2"

titleBlacklist:
  - "Manager"
  - "Senior"
